config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"

  resources :employees, only: [:show, :index, :update_role] do
    patch :update_role, on: :member # PATCH request /employees/:id/update_role
  end

  resources :projects do
    resources :tickets do
      patch :close_ticket, on: :member # PATCH request /projects/:project_id/tickets/:id/close_ticket
    end
  end

  # Additional non-nested route for all tickets
  resources :tickets, only: [:index] do
    collection do
      get :all_tickets
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  # VALIDATIONS
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true

  # ASSOCIATIONS
  belongs_to :created_by, class_name: 'User', foreign_key: 'created_by_id'
  belongs_to :updated_by, class_name: 'User', foreign_key: 'updated_by_id', optional: true
  belongs_to :lead_dev, class_name: 'User', foreign_key: 'lead_dev_id', optional: true
  belongs_to :manager, class_name: 'User', foreign_key: 'manager_id', optional: true

  has_many :tickets, dependent: :destroy

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[show update edit destroy]

  def new
    @project = Project.new
    authorize @project, :new?
    # @user = User.find(params[:user]) if params[:user]
  end

  def create
    @project = Project.new(project_params)
    @project.created_by = current_user
    authorize @project, :create?

    if @project.save
      redirect_to projects_path, notice: "Your project was saved"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    authorize @project, :show?
  end

  def index
    @projects = policy_scope(Project) # Project.all
  end

  def edit
    authorize @project, :edit?
  end

  def update
    if @project.update(project_params)
      # Check if any attributes have changed
      if @project.saved_changes?
        @project.updated_by = current_user
        @project.save
      end
      redirect_to projects_path, notice: "Your project was successfully updated"
    else
      # Handle validation errors or other issues
      render :new, status: :unprocessable_entity
    end
    authorize @project, :update?
  end

  def destroy
    @project.destroy
    redirect_to projects_path, status: :see_other
    authorize @project, :destroy?
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :start_date, :target_date)
  end

  def set_project
    @project = Project.find(params[:id])
    authorize @project # For Pundit, authorize individual instances in other actions
  end
end

app/views/projects/_form.html.erb
<% if user_signed_in? %>
  <%= form_with model: project do |f|%>
    <%= f.label :title, 'Project title' %>
    <%= f.text_field :title %>
    <%= f.label :description, 'About the project' %>
    <%= f.text_area :description %>
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
    <%= f.label :target_date %>
    <%= f.date_field :target_date %>
    <%= f.submit %>
  <% end %>
  <% else %>
    <%= link_to 'Please sign in', new_user_session_path %>

  <% end %>

app/views/projects/edit.html.erb
<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<h1 class="text-lg text-black font-semibold">All Projects</h1>
<div class=""></div>
<ol>
  <% @projects.each_with_index do |project, index| %>
    <li>
      <%= link_to project.title, project_path(project), class:  %>
      <span><%= index %></span>
      <%# <%= link_to 'X', destroy_project_path(project) %>
      <%= link_to project,
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
        class: "btn ml-4" do %>
        X
      <% end %>
    </li>
  <% end %>
</ol>
<% @projects.each_with_index do |project, index| %>

<% end %>

app/views/projects/new.html.erb
<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<div class="container">
  <%= @project.title %>
  Start: <%= @project.start_date %>
  End: <%= @project.target_date %>

  <%= link_to "Delete",
  project_path(@project),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
</div>